// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://icekfttmjohsczyzphxz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImljZWtmdHRtam9oc2N6eXpwaHh6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTEwMzQ0NjgsImV4cCI6MjA2NjYxMDQ2OH0.NWUzxRxjRxah-afQjqzNiu2KKvUoQ_nAOlOqn3_ZotI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});